{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "platform-poc.serviceAccountName" . }}
  labels:
{{ include "platform-poc.labels" . | indent 4 }}
{{- end -}}
